version = 1

[[analyzers]]
name = "cxx"

[[analyzers]]
name = "sql"

[[analyzers]]
name = "docker"

[[analyzers]]
name = "php"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

[[analyzers]]
name = "javascript"